module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-sass-guidelines'],
  plugins: ['stylelint-order'],
  rules: {
    'order/properties-alphabetical-order': null,
    'declaration-empty-line-before': null,
    'scss/dollar-variable-pattern': /^[a-z]+([A-Z]{1}[a-z]+)+$|^[a-z]+(-\w+)+|[a-z]+|[A-Z]/, // 1、匹配小驼峰 2、匹配小字母中划线 3、匹配小字母组合
    'scss/at-function-pattern': /^[a-z]+([A-Z]{1}[a-z]+)+$|^[a-z]+(-\w+)+|[a-z]+/, // 1、匹配小驼峰 2、匹配小字母中划线 3、匹配小字母组合
    'selector-class-pattern': /^[a-z]+[(--|-|__).+]?/,
    'order/properties-order': [
      {
        groundName: 'Position',
        properties: ['position', 'top', 'right', 'bottom', 'left'],
      },
      {
        groundName: 'Display & Flow',
        properties: ['display', 'visibility', 'float', 'clear'],
      },
      {
        groundName: 'Box',
        properties: [
          'width',
          'min-width',
          'max-width',
          'height',
          'min-height',
          'max-height',
          'border',
          'border-width',
          'border-top-width',
          'border-right-width',
          'border-bottom-width',
          'border-left-width',
          'border-style',
          'border-top-style',
          'border-right-style',
          'border-bottom-style',
          'border-left-style',
          'border-color',
          'border-top-color',
          'border-right-color',
          'border-bottom-color',
          'border-left-color',
          'border-image',
          'border-image-source',
          'border-image-slice',
          'border-image-width',
          'border-image-outset',
          'border-image-repeat',
          'border-top',
          'border-top-width',
          'border-top-style',
          'border-top-color',
          'border-top',
          'border-right-width',
          'border-right-style',
          'border-right-color',
          'border-bottom',
          'border-bottom-width',
          'border-bottom-style',
          'border-bottom-color',
          'border-left',
          'border-left-width',
          'border-left-style',
          'border-left-color',
          'border-radius',
          'border-top-right-radius',
          'border-bottom-right-radius',
          'border-bottom-left-radius',
          'border-top-left-radius',
        ],
      },
      {
        groupName: 'Backgrounds',
        properties: [
          'background',
          'background-color',
          'background-image',
          'background-repeat',
          'background-position',
        ],
      },
    ],
  },
};
